### PR TITLE
Add `routeChangeValidator`, default route comparison

### LINKED ISSUE #320: Query param changes reset focus in v2.1
I'm not sure if this is a bug, but it is a change from v2.0.

We have inputs in our application that store the entered data in a query param (search/filter/etc). With v2.1 whenever data is entered into these inputs focus is lost as the query param changes. This is essentially unusable. We debounce the input, but any slight pause in the users typing resets the focus away.

Is this a bug that can be fixed here?
or
Is there a way we can change our application to continue to store this meaningful data in the URL and still use this addon?

eg (striped way down):
```
{{!-- application.hbs --}}
<NavigationNarrator/>
<Input {{on "input" this.setFilter}} />
```

```
//controllers/application.js
export default class ApplicationController extends Controller {
  queryParams = ['filter'];
  @tracked filter;

  @action
  setFilter(evt) {
    this.filter = evt.target.value;
  }
}
```

I can also create this as a reproduction repo if that is clearer.

cc @MelSumner as this is probably caused by changes to the route event in #306

### PR DESCRIPTION
**Pull request by MelSumner**
## Summary

If merged, this PR adds a way to support custom focus requirements. Potentially resolves #320 

It also changes the default behavior to only trigger refocus if the route, params, or query params change. Consequently `routerService.refresh()` will *not* trigger a refocus. We believe this is a desirable default behavior.

Please review both the technical approach, and the documentation added to the README about the feature.

### CODE REVIEW

**Comment by MelSumner** [comment]
Update: converting to draft after a discussion on Discord, but please still leave review/feedback if you can.

**Comment by MelSumner** [comment]
@ef4 @chancancode Could you both look at this approach and LMK what you think?

**Comment by ef4** [comment]
I have two concerns with this approach.

One is that I think we could probably offer a better default. For example, is it *ever* correct to refocus when the URL didn't change? It seems unlikely, so maybe the default validator could implement that behavior.

Two is that I don't think validators should be responsible for keeping their own state. I'm pretty sure the `routeDidChange` event gives you an argument that has both `from` and `to` properties describing exactly what's changing. I think validators should look at that to make their decision, and not try to remember what they saw last.

**Comment by jgwhite** [comment]
Strong agree with both @ef4's comments. The validator managing its own state is my fault — I forgot that `routeDidChange` receives the transition when we first spiked this.

**Comment by jgwhite** [comment]
I’ve updated this in line with @ef4’s feedback. The `routeInfoEqual` util needs better test coverage, but apart from that I think this is headed in the right direction.

**Comment by jgwhite** [comment]
Oh, and the component test needs updated to pass a mock transition.

**Comment by jgwhite** [comment]
I think this is in a good spot for another review. I’ve tidied it up and squashed it down to one commit for clarity. @ef4 your review would be greatly appreciated.

**Review by ef4 — APPROVED** [review]
Looking good. The only refinement I'd suggest considering is making it easy for people to access the default validator, so they can extend it without completely replacing it.

Something like:

```js
 import Controller from '@ember/controller';
 import { defaultValidator } from 'ember-a11y-refocus';
 export default class ApplicationController extends Controller {
   myCustomValidator(transition) {
     if (transition.from.name === 'special') {
        return false;
     } else {
        return defaultValidator(transition);
     }
   }
 }
```

**Review by josephdsumner — APPROVED** [review]

**Pull request merged**
